Repository FE08-07-projectWiki/LuckyWiki, pull requests merged in 2024-09, with the labels that each got.

#8 Feature-wiki, wikilist 페이지 퍼블리싱
  components/@shared/Header.tsx
  components/Wiki/ProfileDetail.module.scss
  components/Wiki/ProfileDetails.tsx
  components/Wiki/WikiContent.module.scss
  components/Wiki/WikiContent.tsx
  components/Wiki/WikiTitle.module.scss
  components/Wiki/WikiTitle.tsx
  components/WikiList/WikiCard.module.scss
  components/WikiList/WikiCard.tsx
  lib/api.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/wiki/[code].module.scss
  pages/wiki/[code].tsx
  pages/wikilist/WikiList.module.scss
  pages/wikilist/index.tsx
  public/icon/icon-alarm.png
  public/icon/icon-instagram.png
  public/icon/icon-link.png
  public/icon/icon-profile.png
  types/types.ts
Labels: 💻API, 🎨Design, ✨Feat

#10 Feature-wiki페이지 bug해결
  components/@shared/Header.module.scss
  components/Wiki/ProfileDetails.tsx
  package-lock.json
  pages/wiki/[code].module.scss
  pages/wiki/[code].tsx
Labels: 🐛Bug

#12 Feat - 전역 유저 기능 Context API 및 getUser, getProfile 함수 제작
  .eslintrc.json
  apis/auth/authenticateLogin.ts
  apis/auth/authenticateSignUp.ts
  apis/auth/getProfile.ts
  apis/auth/getUser.ts
  components/@shared/Header.tsx
  contexts/AuthProvider.tsx
  contexts/Providers.tsx
  pages/_app.tsx
  pages/login/index.tsx
  pages/signup/index.tsx
  public/icon/icon-no-profile.png
  utils/getTokens.ts
Labels: ✨Feat

#13 Feature - Header 드랍다운 메뉴 기능 구현
  apis/auth/getUser.ts
  components/@shared/Header.tsx
  components/@shared/Header/Header.module.scss
  components/@shared/Header/Header.tsx
  components/@shared/Header/LoggedInUserDropdown.tsx
  components/@shared/Header/MobileUserMenu.tsx
  components/@shared/Header/UserMenu.tsx
  contexts/AuthProvider.tsx
  next.config.mjs
  pages/_app.tsx
  pages/login/index.tsx
  pages/signup/index.tsx
Labels: 🎨Design, 🐛Bug, ✨Feat

#15 Feat - 전역에서 선언적으로 사용 가능한 스낵바 호출 커스텀 훅 제작
  components/@shared/Header/Header.tsx
  contexts/AuthProvider.tsx
  contexts/Providers.tsx
  contexts/SnackbarProvider.tsx
  public/icon/icon-error.png
  public/icon/icon-success.png
  styles/globals.scss
Labels: ✨Feat

#18 Feat - 위키 검색하기
  apis/auth/getProfileList.ts
  components/@shared/Header.tsx
  components/Wiki/ProfileDetail.module.scss
  components/Wiki/ProfileDetails.tsx
  components/Wiki/WikiTitle.tsx
  components/WikiList/SPinner.tsx
  components/WikiList/SearchForm.module.scss
  components/WikiList/SearchForm.tsx
  components/WikiList/Spinner.module.scss
  components/WikiList/WikiCard.module.scss
  components/WikiList/WikiCard.tsx
  hooks/useDebounce.ts
  lib/api.ts
  package-lock.json
  package.json
  pages/wiki/[code].module.scss
  pages/wiki/[code].tsx
  pages/wikilist/WikiList.module.scss
  pages/wikilist/index.tsx
  public/icon/icon-no-search.png
  public/icon/icon-spinner.png
  test.http
  types/types.ts
Labels: 🎨Design, ✨Feat

#24 Feature - 리프레시 토큰으로 새로운 엑세스 토큰을 받아와야 하는 API 요청 함수들에 포함될 공통 로직 구현
  apis/auth/authenticateLogin.ts
  apis/auth/createProfile.ts
  apis/auth/fetchWithTokenRefresh.ts
  apis/auth/getUser.ts
  apis/auth/updatePassword.ts
  contexts/AuthProvider.tsx
  middleware.ts
  utils/getServerTokens.ts
Labels: ✨Feat, ♻️Refactor

#25 fix - AuthProvider 컴포넌트, fetchWithTokenRefresh 함수에서 버그가 발생하는 부분 수정
  apis/auth/createProfile.ts
  apis/auth/fetchWithTokenRefresh.ts
  apis/auth/getUser.ts
  apis/auth/updateSecurityQuiz.ts
  components/@shared/Input/ValidInput.tsx
  components/myPage/CreateWikiForm.tsx
  components/myPage/UpdateSecurityQuizForm.tsx
  components/myPage/WikiQuiz.tsx
  contexts/AuthProvider.tsx
  hooks/useValidForm.ts
  pages/mypage/index.tsx
  types/types.ts
Labels: 🐛Bug

#27 Feat - WikiEdit 페이지 및 기능 구현
  apis/auth/patchUser.ts
  apis/auth/uploadImages.ts
  components/Wiki/WikiContent.tsx
  components/WikiEdit/EditInput/EditImageInput.module.scss
  components/WikiEdit/EditInput/EditImageInput.tsx
  components/WikiEdit/EditInput/EditInput.module.scss
  components/WikiEdit/EditInput/EditInput.tsx
  components/WikiEdit/WIkiEditForm.module.scss
  components/WikiEdit/WikiEditContent.module.scss
  components/WikiEdit/WikiEditContent.tsx
  components/WikiEdit/WikiEditForm.tsx
  components/WikiEdit/WikiEditProfile.module.scss
  components/WikiEdit/WikiEditProfile.tsx
  components/WikiEdit/types/EditTypes.ts
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.tsx
  pages/wiki/[code]/edit/index.tsx
  public/icon/icon-camera.png
  styles/quillCustom.scss
Labels: 💻API, 🎨Design, ✨Feat

#29 Feat - WikiList 페이지 무한 스크롤 구현, 위키 검색 기능 수정
  apis/auth/getProfileList.ts
  components/@shared/Header.tsx
  components/WikiList/SearchForm.module.scss
  components/WikiList/SearchForm.tsx
  components/WikiList/WikiCard.tsx
  next.config.mjs
  pages/wikilist/WikiList.module.scss
  pages/wikilist/index.tsx
  test.http
Labels: ✨Feat, ♻️Refactor

#32 Fix - 프로필 카드에서 id 제거 후 사용되지 않는 변수로 인한 lint 에러 제거
  components/home/ProfileCard.tsx
  next.config.mjs
Labels: 🐛Bug

#34 Feature - Polling으로 서버와 주기적으로 연동하여 알림을 받는 기능 및 createPortal로 알림 모달 구현
  apis/auth/deleteNotification.ts
  apis/auth/fetchWithTokenRefresh.ts
  apis/auth/getNotifications.ts
  components/@shared/Header/Header.module.scss
  components/@shared/Header/Header.tsx
  components/@shared/Header/MobileUserMenu.tsx
  components/@shared/Header/UserMenu.tsx
  components/@shared/header/Alarm.module.scss
  components/@shared/header/Alarm.tsx
  components/@shared/header/MobileUserMenu.module.scss
  components/@shared/header/UserMenu.module.scss
  components/@shared/modal/BackDrop.module.scss
  components/@shared/modal/BackDrop.tsx
  components/@shared/modal/Portal.tsx
  components/@shared/modal/notification/NotificationCard.module.scss
  components/@shared/modal/notification/NotificationCard.tsx
  components/@shared/modal/notification/NotificationModal.module.scss
  components/@shared/modal/notification/NotificationModal.tsx
  contexts/AuthProvider.tsx
  hooks/useModal.ts
  next.config.mjs
  pages/_document.tsx
  public/icon/icon-close-gray.png
  public/icon/icon-close.png
  types/types.ts
  utils/getElapsedPeriod.ts
Labels: ✨Feat

#36 Feat - WikiList 페이지에 최근 검색한 목록 표시, Wiki 페이지에 프로필 디테일 내용 접기/펼치기 기능
  components/Wiki/ProfileDetail.module.scss
  components/Wiki/ProfileDetails.tsx
  components/Wiki/WikiContent.module.scss
  components/Wiki/WikiContent.tsx
  components/Wiki/WikiTitle.module.scss
  components/WikiList/SearchForm.tsx
  components/WikiList/TheLatestSearch.module.scss
  components/WikiList/TheLatestSearch.tsx
  components/WikiList/WikiCard.module.scss
  components/WikiList/types/SearchType.ts
  pages/wikilist/WikiList.module.scss
  pages/wikilist/index.tsx
  public/icon/icon-less-button.png
  public/icon/icon-more-button.png
  styles/_mixins.scss
Labels: 🎨Design, ✨Feat, ♻️Refactor

#38 Feature - 위키 생성 및 인증 질문 변경 시 옵션으로 이메일로 질문과 답변을 보내주는 기능 구현
  components/@shared/header/Alarm.module.scss
  components/@shared/header/Alarm.tsx
  components/myPage/CreateWikiForm.tsx
  components/myPage/SendEmailInput.tsx
  components/myPage/UpdateSecurityQuizForm.tsx
  package-lock.json
  package.json
  styles/globals.scss
  utils/sendMail.ts
Labels: ✨Feat

#39 Refactor - 유효성 검사 커스텀훅 최적화 작업
  .eslintrc.json
  components/@shared/Input/ValidInput.tsx
  components/myPage/CreateWikiForm.tsx
  components/myPage/SendEmailInput.tsx
  components/myPage/UpdatePasswordForm.tsx
  components/myPage/UpdateSecurityQuizForm.tsx
  constants/validOptions.ts
  hooks/useValidForm.ts
  pages/login/index.tsx
  pages/signup/index.tsx
Labels: ♻️Refactor

#41 Fix - updatePassword()에서 삭제된 FormInputValues 타입을 import 하던 것 수정
  apis/auth/updatePassword.ts
  pages/home/index.tsx
Labels: 🐛Bug

#42 Feature - Modal 컴포넌트 제작, 편집 관련 로직 추가
  apis/auth/updatePing.ts
  components/@shared/modal/Modal.module.scss
  components/@shared/modal/Modal.tsx
  components/Wiki/ProfileDetail.module.scss
  components/Wiki/ProfileDetails.tsx
  components/Wiki/WikiTitle.module.scss
  components/Wiki/WikiTitle.tsx
  components/WikiEdit/EditInput/EditInput.module.scss
  components/WikiEdit/EditInput/EditInput.tsx
  components/WikiEdit/WikiEditContent.module.scss
  components/WikiEdit/WikiEditForm.tsx
  components/WikiEdit/WikiEditProfile.module.scss
  components/WikiEdit/WikiEditProfile.tsx
  pages/wiki/[code].tsx
  pages/wiki/[code]/edit/index.tsx
  public/icon/icon-lock.png
  styles/_variables.scss
Labels: 💻API, 🎨Design, ✨Feat

#44 #40 삭제된 FormInputValues 타입을 import 하는 부분 제거
  contexts/AuthProvider.tsx
Labels: 🐛Bug

#46 Refactor - 검색 기능 전역적으로 관리, 커스텀 훅 생성
  .vscode/settings.json
  components/@shared/Header/UserMenu.tsx
  components/Wiki/WikiTitle.tsx
  components/WikiEdit/WikiEditContent.tsx
  components/WikiList/SearchForm.tsx
  components/WikiList/TheLatestSearch.module.scss
  components/WikiList/TheLatestSearch.tsx
  components/WikiList/WikiCard.tsx
  components/WikiList/types/SearchType.ts
  contexts/Providers.tsx
  contexts/SearchProvider.tsx
  hooks/WikiList/useLatestSearch.ts
  hooks/WikiList/useNavigate.ts
  hooks/WikiList/useWikiInfiniteScroll.ts
  hooks/useCopyLink.ts
  package-lock.json
  package.json
  pages/wiki/[code].module.scss
  pages/wikilist/index.tsx
  public/icon/icon-facebook.png
  public/icon/icon-twitter.png
Labels: 🎨Design, ♻️Refactor

#49 fix - 헤더 검색창에 검색했을 때 최근 검색어로 적용되지 않는 버그
  components/@shared/Header/UserMenu.tsx
  components/Wiki/ProfileDetails.tsx
  components/Wiki/WikiTitle.tsx
  components/WikiList/RecentSearch.module.scss
  components/WikiList/RecentSearch.tsx
  components/WikiList/SearchForm.tsx
  components/WikiList/types/SearchType.ts
  contexts/SearchProvider.tsx
  hooks/WikiList/useLatestSearch.ts
  hooks/WikiList/useRecentSearch.ts
  hooks/WikiList/useWikiInfiniteScroll.ts
  pages/wiki/[code].module.scss
  pages/wikilist/index.tsx
  public/icon/icon-facebook.png
  public/icon/icon-twitter.png
Labels: 🎨Design, 🐛Bug, ♻️Refactor

#61 Fix - 검색했을 때 검색한 위키가 모두 로드되지 않는 버그 수정, 미비사항 처리
  components/Wiki/ProfileDetail.module.scss
  components/Wiki/ProfileDetails.tsx
  components/Wiki/WikiTitle.module.scss
  components/Wiki/WikiTitle.tsx
  components/WikiList/SearchForm.tsx
  components/WikiList/WikiCard.module.scss
  components/WikiList/WikiCard.tsx
  hooks/WikiList/useWikiInfiniteScroll.ts
  hooks/useDebounce.ts
  hooks/useMessage.ts
  package-lock.json
  package.json
Labels: 🐛Bug, ✨Feat

#60 Hotfix - 민찬: 배포 전 미비 사항 처리 및 버그 수정
  apis/auth/getProfile.ts
  apis/auth/updatePassword.ts
  components/@shared/header/Alarm.tsx
  components/@shared/header/Header.tsx
  components/@shared/header/LoggedInUserDropdown.tsx
  components/@shared/header/MobileUserMenu.tsx
  components/@shared/header/UserMenu.tsx
  components/home/ProfileCard.module.scss
  components/home/ProfileCard.tsx
  pages/home/index.tsx
  styles/globals.scss
  types/types.ts
Labels: 🩹HotFix

#62 Hotfix - 윈도우 운영체제에서 좌우스크롤 제거 및 마이페이지 위키 생성, 변경 폼 타이틀 추가
  pages/mypage/index.tsx
  styles/globals.scss
Labels: 🎨Design, 🐛Bug

#65 Fix/#63/5분 초과 로직 수정
  apis/auth/fetchWithTokenRefresh.ts
  apis/auth/patchUser.ts
  apis/auth/updatePing.ts
  apis/auth/uploadImages.ts
  components/@shared/modal/Modal.module.scss
  components/@shared/modal/Modal.tsx
  components/WikiEdit/EditInput/EditInput.module.scss
  components/WikiEdit/WIkiEditForm.module.scss
  components/WikiEdit/WikiEditForm.tsx
  components/WikiEdit/WikiEditProfile.tsx
  hooks/usePingTimer.ts
  pages/wiki/[code].tsx
  pages/wiki/[code]/edit/index.tsx
Labels: 🩹HotFix, ✨Feat

#66 #54 fix: 실제 모바일 환경을 고려한 이미지 비율 조정
  pages/_app.tsx
  pages/_document.tsx
  pages/landing/Landing.module.scss
Labels: 🐛Bug

#73 Fix- 회원가입, 로그인 실패 메세지 수정
  apis/auth/authenticateLogin.ts
  apis/auth/authenticateSignUp.ts
  contexts/AuthProvider.tsx
  contexts/SnackbarProvider.tsx
  pages/signup/index.tsx
Labels: 💻API, ♻️Refactor

#77 #21 fix: 실제 모바일 환경에서 이미지 비율 깨짐 수정
  pages/landing/Landing.module.scss
Labels: 🐛Bug

#79 Design - 변경된 이미지와 로고를 반영하여 랜딩 페이지 수정
  components/@shared/header/Header.tsx
  components/home/ProfileCard.module.scss
  pages/home/Home.module.scss
  pages/landing/Landing.module.scss
  pages/landing/index.tsx
  public/icon/icon-no-profile.png
  public/landing/landing-ellipse.png
  public/landing/landing-profile.png
  public/logo/logo_main.png
  styles/_variables.scss
Labels: 🎨Design, 🐛Bug

#81 Fix - 헤더 알람 아이콘 위치 조정
  components/@shared/header/Alarm.module.scss
Labels: 🎨Design

#91 Hotfix - 랜딩 페이지 윈도우 해상도에서 로고 크키 커짐 이슈 및 이미지 카드 비율 문제 해결
  components/@shared/header/Header.tsx
  components/home/ProfileCard.module.scss
  components/home/ProfileCard.tsx
  pages/landing/Landing.module.scss
  public/logo/logo_main.png
Labels: 🎨Design, 🐛Bug

#97 Design - 로딩스피너 위치 수정, zIndex제거
  components/wikiEdit/WikiEditContent.module.scss
  components/wikiEdit/WikiEditContent.tsx
Labels: 🎨Design
